#!/usr/bin/env bash

. "$SETUP_PATH/lib/env"

log_info "Starting setup (FORCE=$FORCE)..."

bash "$SETUP_PATH/tasks/pac-man" "$@" || exit 1
bash "$SETUP_PATH/tasks/packages" "$@" || exit 1
bash "$SETUP_PATH/tasks/fonts" "$@" || exit 1
bash "$SETUP_PATH/tasks/neovim" "$@" || exit 1
bash "$SETUP_PATH/tasks/tmux" "$@" || exit 1
bash "$SETUP_PATH/tasks/zsh-plugins" "$@" || exit 1
bash "$SETUP_PATH/tasks/services" "$@" || exit 1

log_step 'Setup Complete!'
