#!/usr/bin/env bash

. "$SETUP_PATH/lib"

log_step 'Installing kanata...'
yay -S --noconfirm --needed kanata-bin || {
    log_error "kanata installation failed"
    return 1
}

service_file="$HOME/.config/systemd/user/kanata.service"
if [[ ! -f "$service_file" ]] || (( FORCE == 1 )); then
    log_info 'Creating kanata.service'
    ensure_dir "${service_file%/*}"
    cat > "$service_file" <<-EOF
[Unit]
Description=Kanata keyboard remapper
Documentation=https://github.com/jtroo/kanata

[Service]
Type=simple
ExecStart=$(which kanata) --no-wait
Restart=on-failure
RestartSec=3

[Install]
WantedBy=default.target
EOF
fi

sudo groupdel uinput 2>/dev/null
sudo groupadd --system uinput

sudo usermod -aG input $USER
sudo usermod -aG uinput $USER

sudo modprobe uinput

sudo tee /etc/udev/rules.d/99-input.rules > /dev/null << EOF
KERNEL=="uinput", MODE="0660", GROUP="uinput", OPTIONS+="static_node=uinput"
EOF
sudo udevadm control --reload-rules && sudo udevadm trigger

systemd_user_enable 'kanata.service'
