#!/usr/bin/env bash

. "$SETUP_PATH/lib"

log_step "Installing themes..."

# gtk-2.0 dependencies
# yay -S --noconfirm --needed gtk-engine-murrine gtk-engines

yay -S --noconfirm --needed matcha-gtk-theme bibata-cursor-theme-bin

sudo pacman -S --noconfirm --needed papirus-icon-theme 
