#!/usr/bin/bash
read volume_percent is_sink_muted is_source_muted <<< $(pulseaudio-ctl full-status)
# echo VOL $volume_percent% $is_sink_muted $is_source_muted
if [[ $is_sink_muted == "no" ]] ; then
	echo "%{F#f8d}VOL%{F-} $volume_percent%"
else
	echo "%{F#f8d}VOL%{F-} %{F#aaa}muted%{F-}"
fi

#if [[ $is_source_muted == "yes" ]] ; then
#	echo " " +  󰍭
#fi
