#!/usr/bin/env bash

. "$SETUP_PATH/lib"

log_step "Installing zsh..."
sudo pacman -S --noconfirm --needed zsh || {
    log_error "zsh installation failed"
    return 1
}

sudo chsh -s "$(command -v zsh)" "$USER"

plugins_file="$SETUP_PATH/data/zsh-plugins.txt"
plugins_dir="$HOME/.zsh/plugins"
failed=()

if [[ ! -f "$plugins_file" ]]; then
    log_error "Plugin list not found: $plugins_file"
    return 1
fi

ensure_dir "$plugins_dir"

while IFS= read -r url; do
    git_clone_or_update "$url" "$plugins_dir/${url##*/}" || failed+=("$url")
done < <(read_list "$plugins_file")

if (( ${#failed[@]} > 0 )); then
    log_error "Failed to install some plugins: ${failed[*]}"
fi
