#!/usr/bin/env bash

grep -E '^(ID|ID_LIKE)=' /etc/os-release | grep -q arch || {
    echo "Script only meant for arch based distro"
    exit 1
}

# Ensure repo cache is up-to-date and upgrade packages
sudo pacman -Syu --noconfirm

# Ensure necessary dependencies
sudo pacman -S --noconfirm --needed base-devel git

# Install aur helper (yay)
git clone https://aur.archlinux.org/yay-bin.git /tmp/yay
(
    cd /tmp/yay
    makepkg -si
)

# Install pacman pkgs
mapfile -t PKGS < <(read_list "${SETUP_PATH-$HOME/.config/setup}"/data/pacman-packages.txt)
sudo pacman -S --noconfirm --needed "${PKGS[@]}"

# Install yay pkgs
mapfile -t PKGS < <(read_list "${SETUP_PATH-$HOME/.config/setup}"/data/aur-packages.txt)
yay -S --noconfirm --needed "${PKGS[@]}"
