#!/usr/bin/env bash

export SETUP_PATH=$HOME/.config/setup

for file in "$SETUP_PATH"/*; do
    if [[ "${file##*/}" =~ [0-9][0-9].* ]]; then
        echo "Sourcing $file..."
        . "$file"
    fi
done
