#!/usr/bin/env bash

SETUP_PATH="$HOME/.config/setup"
export SETUP_PATH

FORCE=0

while (( $# > 0 )); do
    case "$1" in
        -f|--force)
            FORCE=1
            shift
            ;;
        *)
            echo "Unknown argument: $1"
            exit 1
            ;;
    esac
done
export FORCE

if [[ ! -f /etc/os-release ]]; then
	echo "Error: /etc/os-release not found."
	exit 1
fi

if ! grep -qEi '^ID(_LIKE)?=.*arch' /etc/os-release; then
	echo "Error: Arch Linux not detected."
	exit 1
fi

. "$SETUP_PATH/tasks/update-system-packages"
. "$SETUP_PATH/tasks/prerequisites"
. "$SETUP_PATH/tasks/yay"
. "$SETUP_PATH/tasks/packages"
. "$SETUP_PATH/tasks/nerd-fonts"
. "$SETUP_PATH/tasks/kanata"

. "$SETUP_PATH/tasks/terminal-installer"
. "$SETUP_PATH/tasks/desktop-installer"

