#!/bin/bash


capacity=$(upower -d | grep percentage -m 1 | awk '{ print $2 }' | tr -d "%")
status=$(upower -d | grep state -m 1 | awk '{ print $2 }')

last_notfified_file="/tmp/battery_last_notified"

if [[ ! -f $last_notfified_file ]]; then
    touch $last_notfified_file
fi

last_notified=$(cat $last_notfified_file)

output="$capacity%"
threshold=15
notification_interval_seconds=60

if [[ $status == "discharging" ]]; then
    if [[ $capacity -le $threshold ]]; then
        output="%{F#f00}BAT $output%{F-}"
        now=$(date +%s)
        if [[ $((now - last_notified)) -gt $notification_interval_seconds ]]; then
            echo $now > $last_notfified_file
            dunstify -t 30000 -u critical "Battery low" "Battery is at $capacity%"
        fi
    else
        output="%{F#ef2}BAT%{F-} $output"
    fi
else
    output="%{F#8fc}PLG%{F-} $output"
    #dunstctl close
fi

echo $output
