#!/usr/bin/env bash

switch_to() {
    if [[ -z $TMUX ]]; then
        tmux attach-session -t $1
    else
        tmux switch-client -t $1
    fi
}

if [[ "$#" == 1 ]]; then
	selected_project_dir="$1"
else
	projects_dir="$HOME/projects"
	selected_project_dir=$(find $projects_dir -mindepth 2 -maxdepth 2 -type d | fzf)
fi

selected_project_name=$(basename "$selected_project_dir" | tr . -)

while [[ ${selected_project_name:0:1} == "-" ]]; do
	selected_project_name=${selected_project_name:1}
done

if [[ -z $selected_project_name ]]; then
    exit 0
fi

if ! tmux has-session -t=$selected_project_name 2> /dev/null; then
    tmux new-session -ds $selected_project_name -c $selected_project_dir \; new-window -c $selected_project_dir -t $selected_project_name \; select-window -t $selected_project_name:1
fi

switch_to $selected_project_name
