#!/bin/sh

wallpaper_dir="$HOME/wallpapers"
if [ ! -f $1 ]; then
    echo "$1 not found!"
else
    file_path=$(dirname $1)
    file_name=$(basename $1)
    if [[ $file_path != $wallpaper_dir && $file_path != "." ]]; then
        cp $1 $wallpaper_dir
    fi
    ln -s $1 "$wallpaper_dir/current/$file_name" 
fi

